import DashboardLayout from "@/components/DashboardLayout";
import SensitiveValue from "@/components/SensitiveValue";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2, CircleAlert, LockKeyhole, Play, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { formatMoney } from "@/lib/financialDisplay";

type ApprovalActionType = "cash_event" | "transfer" | "trade" | "budget_adjustment" | "period_adjustment";
const actionName: Record<ApprovalActionType, string> = { cash_event: "حركة نقدية", transfer: "تحويل", trade: "صفقة تداول", budget_adjustment: "تسوية ميزانية", period_adjustment: "إغلاق فترة" };
const statusName: Record<string, string> = { pending: "بانتظار القرار", approved: "معتمدة", rejected: "مرفوضة", expired: "منتهية", executed: "منفذة" };
const errorText = (error: unknown) => error instanceof Error ? error.message : "تعذر إكمال العملية الآن.";
const money = (value: string | null | undefined, currency: string | null | undefined) => value && currency ? <SensitiveValue>{formatMoney(value, currency, 0)}</SensitiveValue> : "—";
const dateTime = (value: number | null | undefined) => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function ApprovalsPage() {
  const utils = trpc.useUtils();
  const requests = trpc.family.governance.requests.useQuery();
  const history = trpc.family.governance.decisionHistory.useQuery();
  const currentUser = trpc.auth.me.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const decide = trpc.family.governance.decide.useMutation({ onSuccess: () => { toast.success("تم تسجيل قرار الاعتماد."); void utils.family.governance.requests.invalidate(); void utils.family.governance.decisionHistory.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const executeCash = trpc.family.ledger.executeApprovedCash.useMutation({ onSuccess: () => { toast.success("نُشرت الحركة النقدية المعتمدة."); void utils.family.governance.requests.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const executeTransfer = trpc.family.ledger.executeApprovedTransfer.useMutation({ onSuccess: () => { toast.success("نُشر التحويل المعتمد."); void utils.family.governance.requests.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const executeTrade = trpc.family.ledger.executeApprovedTrade.useMutation({ onSuccess: () => { toast.success("نُشرت الصفقة المعتمدة."); void utils.family.governance.requests.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const executeBudget = trpc.family.governance.executeApprovedBudgetAdjustment.useMutation({ onSuccess: () => { toast.success("نُفذت تسوية الميزانية المعتمدة."); void utils.family.governance.requests.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const closePeriod = trpc.family.governance.closeApprovedPeriod.useMutation({ onSuccess: () => { toast.success("أُغلقت الفترة المعتمدة."); void utils.family.governance.requests.invalidate(); }, onError: error => toast.error(errorText(error)) });
  const selected = useMemo(() => requests.data?.find(item => item.id === selectedId) || requests.data?.[0] || null, [requests.data, selectedId]);
  useEffect(() => { if (requests.data?.length && selectedId === null) setSelectedId(requests.data[0].id); }, [requests.data, selectedId]);
  const execute = (request: { id: number; actionType: ApprovalActionType }) => {
    if (request.actionType === "cash_event") executeCash.mutate({ requestId: request.id });
    if (request.actionType === "transfer") executeTransfer.mutate({ requestId: request.id });
    if (request.actionType === "trade") executeTrade.mutate({ requestId: request.id });
    if (request.actionType === "budget_adjustment") executeBudget.mutate({ requestId: request.id });
    if (request.actionType === "period_adjustment") closePeriod.mutate({ requestId: request.id });
  };
  const isExecuting = executeCash.isPending || executeTransfer.isPending || executeTrade.isPending || executeBudget.isPending || closePeriod.isPending;
  return <DashboardLayout><main className="mx-auto max-w-7xl space-y-6" dir="rtl">
    <header className="rounded-[1.75rem] bg-gradient-to-l from-teal-700 to-slate-950 p-7 text-white"><p className="text-sm text-teal-100">FAMILY / APPROVAL WORKFLOW</p><h1 className="mt-2 text-3xl font-bold">الموافقات والقرارات</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-200">يعرض المسار طلبًا مجمدًا ثم قرارًا مستقلًا ثم تنفيذًا صريحًا. لا يستطيع مقدم الطلب اعتماد طلبه، ولا يترتب على الاعتماد وحده نشر قيد جديد.</p></header>
    <section className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="fintech-surface-card"><CardHeader><CardTitle className="flex items-center gap-2"><LockKeyhole className="size-5 text-primary" />الطلبات</CardTitle><CardDescription>اختر طلبًا لعرض تفاصيله وإجراء القرار المسموح به.</CardDescription></CardHeader><CardContent>{requests.isLoading ? <p className="py-10 text-center text-sm text-muted-foreground">جارٍ تحميل الطلبات…</p> : requests.error ? <p className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{errorText(requests.error)}</p> : requests.data?.length ? <div className="space-y-2">{requests.data.map(request => <button className={`approval-request-row ${selected?.id === request.id ? "is-active" : ""}`} type="button" key={request.id} onClick={() => setSelectedId(request.id)}><span><strong>{actionName[request.actionType as ApprovalActionType] || request.actionType}</strong><small>طلبه {request.requesterName || "عضو العائلة"} · {dateTime(request.createdAt)}</small></span><Badge variant={request.status === "pending" ? "outline" : "secondary"}>{statusName[request.status] || request.status}</Badge></button>)}</div> : <div className="fintech-empty-state"><ShieldCheck className="fintech-empty-state-icon" /><h3>لا توجد طلبات اعتماد</h3><p>ستظهر هنا فقط العمليات التي تجاوزت سياسة اعتماد فعالة وتم تجميد بياناتها للمراجعة.</p></div>}</CardContent></Card>
      <Card className="fintech-surface-card"><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="size-5 text-primary" />تفاصيل الطلب</CardTitle><CardDescription>راجع نوع العملية والمبلغ والمقدم وانتهاء الصلاحية قبل أي قرار أو تنفيذ.</CardDescription></CardHeader><CardContent>{selected ? <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs text-muted-foreground">نوع العملية</p><p className="mt-1 font-bold">{actionName[selected.actionType as ApprovalActionType] || selected.actionType}</p></div><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs text-muted-foreground">القيمة المجمدة</p><p className="mt-1 text-lg font-bold"><SensitiveValue>{money(selected.amount, selected.currency)}</SensitiveValue></p></div><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs text-muted-foreground">مقدم الطلب</p><p className="mt-1 font-semibold">{selected.requesterName || "عضو العائلة"}</p></div><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs text-muted-foreground">انتهاء الطلب</p><p className="mt-1 font-semibold">{dateTime(selected.expiresAt)}</p></div></div><div className="rounded-xl border border-border p-4 text-sm"><p className="font-semibold">حالة الطلب: {statusName[selected.status] || selected.status}</p>{selected.executedEventId ? <p className="mt-2 text-muted-foreground">تم تنفيذ العملية في حدث دفتر رقم #{selected.executedEventId}.</p> : <p className="mt-2 text-muted-foreground">يبقى الطلب منفصلًا عن الدفتر حتى يُنفّذ صراحة بعد الاعتماد.</p>}</div>{selected.status === "pending" && selected.requestedByUserId !== currentUser.data?.id && <div className="flex flex-wrap gap-2"><Button disabled={decide.isPending} onClick={() => decide.mutate({ requestId: selected.id, decision: "approved", note: null, reconfirmed: true })}>اعتماد الطلب</Button><Button variant="outline" disabled={decide.isPending} onClick={() => decide.mutate({ requestId: selected.id, decision: "rejected", note: null, reconfirmed: true })}>رفض الطلب</Button></div>}{selected.status === "pending" && selected.requestedByUserId === currentUser.data?.id && <p className="flex items-center gap-2 rounded-xl bg-muted/50 p-3 text-sm text-muted-foreground"><CircleAlert className="size-4" />لا يمكنك اعتماد أو رفض الطلب الذي أنشأته.</p>}{selected.status === "approved" && <Button disabled={isExecuting} onClick={() => execute({ id: selected.id, actionType: selected.actionType as ApprovalActionType })}><Play className="ml-1 size-4" />تنفيذ البيانات المجمدة</Button>}</div> : <div className="fintech-empty-state"><LockKeyhole className="fintech-empty-state-icon" /><h3>اختر طلبًا</h3><p>حدد طلب اعتماد من القائمة لعرض التفاصيل والإجراءات المتاحة وفق صلاحيتك.</p></div>}</CardContent></Card></section>
    <Card className="fintech-surface-card"><CardHeader><CardTitle>سجل القرارات</CardTitle><CardDescription>يحفظ القرار والمعتمد ووقت الإقرار ومصير التنفيذ ضمن مساحة العائلة فقط.</CardDescription></CardHeader><CardContent>{history.isLoading ? <p className="py-6 text-center text-sm text-muted-foreground">جارٍ تحميل السجل…</p> : history.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-600"><tr><th className="p-3">القرار</th><th className="p-3">الطلب</th><th className="p-3">المعتمد</th><th className="p-3">وقت الإقرار</th><th className="p-3">الحالة</th></tr></thead><tbody className="divide-y">{history.data.map(entry => <tr key={entry.id}><td className="p-3 font-semibold">{entry.decision === "approved" ? "اعتماد" : "رفض"}</td><td className="p-3">#{entry.requestId}</td><td className="p-3">{entry.approverName || "عضو معتمد"}</td><td className="p-3 text-muted-foreground">{dateTime(entry.reconfirmedAt || entry.createdAt)}</td><td className="p-3"><Badge variant="outline">{statusName[entry.requestStatus] || entry.requestStatus}</Badge></td></tr>)}</tbody></table></div> : <p className="py-6 text-center text-sm text-muted-foreground">لا يوجد سجل قرارات بعد.</p>}</CardContent></Card>
  </main></DashboardLayout>;
}
