import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, FileJson, FileSpreadsheet, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const errorText = (error: unknown) => error instanceof Error ? error.message : "تعذر إنشاء التصدير الآن.";

export default function FamilyExportPage() {
  const exportFamily = trpc.family.exports.family.useMutation({ onSuccess: result => { const blob = new Blob([result.content], { type: result.contentType }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = result.filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(href); toast.success("تم إنشاء الملف وتنزيله. سُجلت العملية ضمن سجل التدقيق."); }, onError: error => toast.error(errorText(error)) });
  return <DashboardLayout><main className="mx-auto max-w-5xl space-y-6" dir="rtl"><header className="rounded-[1.75rem] bg-gradient-to-l from-sky-700 to-slate-950 p-7 text-white"><p className="text-sm text-sky-100">FAMILY / PRIVATE EXPORT</p><h1 className="mt-2 text-3xl font-bold">تصدير البيانات العائلية</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-200">ينشأ التصدير عند الطلب للمستشار أو المالك، ويضم قراءات الحسابات والدفتر والحيازات والمستحقات وتقييمات الزكاة ضمن مساحة FAMILY الحالية فقط.</p></header><section className="grid gap-6 md:grid-cols-2"><Card className="fintech-surface-card"><CardHeader><CardTitle className="flex items-center gap-2"><FileJson className="size-5 text-primary" />JSON منظم</CardTitle><CardDescription>نسخة منظمة صالحة للأرشفة أو الاستيراد التحليلي، تشمل البيانات الوصفية ونطاق المساحة والطابع الزمني.</CardDescription></CardHeader><CardContent><Button className="gap-2" disabled={exportFamily.isPending} onClick={() => exportFamily.mutate({ format: "json" })}><Download className="size-4" />تنزيل JSON</Button></CardContent></Card><Card className="fintech-surface-card"><CardHeader><CardTitle className="flex items-center gap-2"><FileSpreadsheet className="size-5 text-primary" />CSV تشغيلي</CardTitle><CardDescription>صفوف موحدة للحسابات والعمليات والمستحقات وتقييمات الزكاة لتسهيل فتحها في أدوات التحليل.</CardDescription></CardHeader><CardContent><Button className="gap-2" variant="outline" disabled={exportFamily.isPending} onClick={() => exportFamily.mutate({ format: "csv" })}><Download className="size-4" />تنزيل CSV</Button></CardContent></Card></section><p className="flex items-start gap-2 rounded-xl bg-muted/50 p-4 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0" />لا تُخزّن نسخة التصدير في التطبيق أو التخزين المحلي للمتصفح. احفظ الملف الناتج في وجهة مؤسسية آمنة، وتعامل معه بصفته بيانات مالية حساسة.</p></main></DashboardLayout>;
}
